<!DOCTYPE html>
<?php
	include("securepage/nfp_password_protect.php");
	include('functions.php');
	include('mapFunctions.php');
	$centerLatLong=getCityLatLong();
	$myMapKey=getMapKey();
	opendb();
	$id=$_GET['id'];

// return to tool used before reloading the page
	if(isset($_GET['tool']))
		$tool=$_GET['tool'];
	else $tool='unconfirmed';
	if(isset($_GET['panel']))
		$panel=$_GET['panel'];
	else $panel="left";

//do any saves necessary
	if(isset($_GET['saveEmail']) && isset($_POST['emailText']))
	{
		$dbh=openPDO();
		saveEmail($_POST['emailText'],$dbh);
	}
	if(isset($_GET['saveZoom']))
	{
		saveZoom("wholeproject", $_POST['zoomLevel'], $id);
	}
/*	if(isset($_GET['assign']))
	{
		$dbh=openPDO();
		assignToNhood($_POST,$dbh);
	}											*/
	if(isset($_GET['savegeo']))
	{
		saveGeo($_POST);
	}
	if (isset($_GET['save']))
	{
		saveUnconfirmedData($_POST);
	}

	if(isset($_GET['page']	))
		$page=$_GET['page'];
	else $page=1;
?>


<html>
<head>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<meta http-equiv="Content-Type" content="text/html" charset="UTF-8" />
	<link rel="stylesheet" type="text/css" href="css/memberStyles.css" />
	<link rel="stylesheet" type="text/css" href="css/headerNav.css" />


<style type="text/css">
.queuebuttons {
	-moz-box-shadow:inset 0px 1px 21px 0px #fce2c1;
	-webkit-box-shadow:inset 0px 1px 21px 0px #fce2c1;
	box-shadow:inset 0px 1px 21px 0px #fce2c1;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffa83d), color-stop(1, #ff760d) );
	background:-moz-linear-gradient( center top, #ffa83d 5%, #ff760d 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffa83d', endColorstr='#ff760d');
	background-color:#ffa83d;
	-moz-border-radius:17px;
	-webkit-border-radius:17px;
	border-radius:17px;
	border:1px solid #eeb44f;
	display:inline-block;
	color:#333033;
	font-family:arial;
	font-size:13px;
	font-weight:bold;
	padding:6px 20px;
	text-decoration:none;
	text-shadow:1px 1px 1px #cc9f52;
}.queuebuttons:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ff760d), color-stop(1, #ffa83d) );
	background:-moz-linear-gradient( center top, #ff760d 5%, #ffa83d 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff760d', endColorstr='#ffa83d');
	background-color:#ff760d;
}.queuebuttons:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>




	<script type="text/javascript"	src="js/mapFunctions.js"> </script>
	<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=<?php echo $myMapKey; ?>></script>
	<script type="text/javascript">
		function ShowHideDivs(idOfDivToShow)
		{
			if(idOfDivToShow == "fullpagediv")
				document.getElementById("fullpagediv").style.display = "block";
			else
				document.getElementById("fullpagediv").style.display = "none";

			if(idOfDivToShow == "leftdiv")
				document.getElementById("leftdiv").style.display = "block";
			else
				document.getElementById("leftdiv").style.display = "none";
		}

		function renderEmail()
		{
			var theDiv = document.getElementById('renderedDiv');
			var theContent = document.getElementById('emailText').value;

			theDiv.innerHTML = theContent;

			document.getElementById('emailTextDiv').style.display='none';
			document.getElementById('renderedDiv').style.display='block';
		}

		function editEmail()
		{
			// var theDiv = document.getElementById('renderedDiv');
			// var theContent = document.getElementById('emailText');

			//theDiv.innerHTML = theContent;

			document.getElementById('emailTextDiv').style.display='block';
			document.getElementById('renderedDiv').style.display='none';
		}
	</script>


<!--	----------------------------------------	-->

<!--	PAGINATION ATTEMPT VIA AJAX	-->
<script type="text/javascript">
//returns a xmlhttp request object
function getXMLHttp()
{
	  var xmlHttp
	  try
	  {//Firefox, Opera 8.0+, Safari
			xmlHttp = new XMLHttpRequest();
	  }
	  catch(e)
	  {//Internet Explorer
			try
			{   xmlHttp = new ActiveXObject("Msxml2.XMLHTTP");    }
			catch(e)
			{ 	try
				{   xmlHttp = new ActiveXObject("Microsoft.XMLHTTP");      }
				catch(e)
				{  	alert("Your browser does not support AJAX!")
					return false;      }
				}
	  }
	  return xmlHttp;
}


function handleRequest(panel, tool, userid, page)
{
	var xmlHttp = getXMLHttp();

	xmlHttp.onreadystatechange = function()
	{
		if(xmlHttp.readyState == 4)
		{	if(panel=="left")
				HandleLeftDiv(xmlHttp.responseText);
			if(panel=="full")
				HandleFullDiv(xmlHttp.responseText);
		}
	}

	xmlHttp.open("GET", "welcomeCommittee-ajax.php?"+tool+"=true&uid="+userid+"&page="+page, true);
	xmlHttp.send(null);
}



function HandleLeftDiv(response)
{
  document.getElementById('leftdiv').innerHTML = response;
  ShowHideDivs('leftdiv');
}
function HandleFullDiv(response)
{
  document.getElementById('fullpagediv').innerHTML = response;
  ShowHideDivs('fullpagediv');
}
</script>


	<script type="text/javascript">
		var poly;
		var map;
		var geocoder;
		var centerMarker;
		function initialize()
		{
				  var myTown = new google.maps.LatLng<?php echo $centerLatLong; ?>;
				  var myOptions = {
					zoom: <?php echo getWCZoom() ?>,
					center: myTown,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				  };
		//create a geocoder to transform addresses into lat and Long
				geocoder= new google.maps.Geocoder();
		//put the map in the proper div
				  map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);


		//add the 'center' marker
			centerMarker = new google.maps.Marker({
					position: myTown, //<?php echo $centerLatLong; ?>,
					map: map,
					icon: "icons/marker_split.png",
					title: "The Center of the Map",
					visible: false
				});


		//add in the NC markers
			<?php  ncImageMarkers();//ncMarkers($ncPinColor); ?>
			<?php //dcMarkers($dcPinColor);
				unacceptedDonorMarkers();
				//unassignedDonorMarkers();
			?>

		//set the active toolPanel from before the page reloaded
			//ShowHideDivs("<?php echo $tool ?>");
			handleRequest('<?php echo $panel ?>', '<?php echo $tool ?>', <?php echo $id ?>, <?php echo $page ?>);




		}//end initialize()
/**	transforms the address in id="address" to coordinates in id="myCoords" when
 *	Encode button is clicked */
		function codeAddress(address, latLongBox) {
			geocoder.geocode( { 'address': address}, function(results, status) {
				if (status == google.maps.GeocoderStatus.OK)
					{
						map.setCenter(results[0].geometry.location);
						var marker = new google.maps.Marker({
							map: map,
							position: results[0].geometry.location
						});
						document.getElementById(latLongBox).value=results[0].geometry.location;
					}
				else
				{alert("Geocode was not successful for the following reason: " + status);}
			});
		}
	</script>
</head>

 <body onload="initialize(); ">

<h1 style="color: #2f4b66; padding: 5px 5px 15px 15px;">Welcome Committee</h1>
<br />



	<!-- TITLE BAR -->
		<div class="gearsWidget" >
				<ul id="adminNav">
		<!--		<li><a href="ncNotes.php?id=<?php //echo $id?>" >Edit NC Notes</a></li>	-->
				<!-- <li><a href="#" onclick="ShowHideDivs('findAddress');">By Neighborhood</a></li> -->
				<li><a href="#" onclick="ShowHideDivs('fullpagediv'); handleRequest('full', 'ncs', <?php echo $id ?>,0);">Contact NCs</a></li>
				<li><a href="#" onclick="ShowHideDivs('fullpagediv'); handleRequest('full', 'dcs', <?php echo $id ?>,0);">Contact DCs</a></li>
				<li><a href="#" onclick="ShowHideDivs('leftdiv'); handleRequest('left', 'geo', <?php echo $id ?>,0);">Find Geocode/Verify Location</a></li>
				<li><a href="#" onclick="ShowHideDivs('fullpagediv'); handleRequest('full', 'email', <?php echo $id ?>,0);">Email Templates</a></li>
				<li><a href="#" onclick="ShowHideDivs('leftdiv'); handleRequest('left', 'unconfirmed', <?php echo $id ?>,1);">Queue</a></li>
				<!--<li><a href="#" onclick="ShowHideDivs('mapToolsDiv');">Other Map Tools</a></li> -->

				</ul>
		</div>

<!-- LEFT DIV (TOOLS)-->
	<div class="leftWidget" id="leftdiv">

	</div>

<!-- FULL DIV (EMAIL, NC AND DC CONTACT LISTS	-->
		<div class="fullWidget" id="fullpagediv" style="display:none;">

		</div>






<!--	The Map	-->
	<div class="mapWidget" id="map_canvas">
		<p style="color:purple">Map attempting to load.....if you've been waiting over 30 seconds,<br />
		first check other webpages to see if your connection to the internet is working. Contact your system administrator for additional assistance.</p>
	</div>


</body>
</html>

<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script> -->
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>
  <script src="js/plugins.js"></script>
  <script src="js/uiFunctions.js"></script>


<?php

function saveUnconfirmedData($_POST)
{
	$dbh=openPDO();
	//debug
		//echo '<script type="text/javascript">alert(saveUnconfirmedData() (at the bottom of welcomeCommittee-ajax.php) has been called!<br/>);</script>';

	//check if the donor has been accepted yet
		$sql=mysql_query("SELECT accepted, WCNotes FROM members WHERE MemberID=".$_POST['ud_memberID']);
		$accepted=mysql_fetch_array($sql);

			$query=$dbh->prepare("UPDATE members SET NHoodID=:nhName, Notes=:notes, PUNotes=:punotes,WCNotes=:wcnotes, latLong=:latlong, WCEmail=:wcEmail, NCEmail=:ncEmail WHERE MemberID=:uID");
		$query->bindParam(':nhName', $nhName);
		$query->bindParam(':notes', $notes);
		$query->bindParam(':punotes', $punotes);
		$query->bindParam(':wcnotes', $wcnotes);
		$query->bindParam(':uID', $uID);
		$query->bindParam(':latlong', $latLong);
		$query->bindParam(':wcEmail', $wcEmail);
		$query->bindParam(':ncEmail', $ncEmail);

		$nhName= $_POST['NHbox'];
		$notes= $_POST['ud_notes'];
		$punotes=$_POST['ud_punotes'];

	//if they've been accepted already, don't replace the status field
		if($accepted['accepted']==1)
			$wcnotes=$accepted['WCNotes'];
		else
			$wcnotes='<p style="width: 360px; background-color: green; color: white; font-size: 16px; font-weight: bolder; padding: 15px; border: 1px solid green; border-radius: 10px;">
			'.getTodaysDate().':  Assigned to NH '.getNHNameFromNhoodID($nhName).' (NC: '.getNCNameFromNhoodID($_POST['NHbox']).'  )</p>';

		$uID=$_POST['ud_memberID'];
		$latLong=$_POST['ud_latLong'];

		if(isset($_POST['wcemail']))
			$wcEmail=1;
		else $wcEmail=0;

		if(isset($_POST['ncemail']))
			$ncEmail=1;
		else $ncEmail=0;

		try
		{
			$query->execute();
//			echo '<script type="text/javascript"> alert("query executed")</script>';
		}
		catch(PDOException $e)
		{
			echo '<script type="text/javascript"> alert("saveUncomfirmedData() has NOT saved. \r\n Error: '.$e->getMessage().'")</script>';
			die();
		}
}//end saveUnconfirmedData()

function saveEmail($content,$dbh)
{

		$query=$dbh->prepare("UPDATE wholeproject SET data=:html WHERE miscName='welcomeEmail'");
		$query->bindParam(':html', $html);

		$html=trim($content);

		try
		{
			$query->execute();
		}
		catch(PDOException $e)
		{
			echo '<script type="text/javascript"> alert("Default welcome email has NOT been saved. \r\n Error: '.$e->getMessage().'")</script>';
			die();
		}


}//end saveEmail()


?>
